from sahi_keemat import bb_get_price,jio_get_price,flip_kart_get_price,get_converted_price

f = open('C:/Users/Dell/PycharmProjects/sahi-keemat/products/aata.csv','w')
f.write('aata')
f.write('\t')
f.write('https://www.bigbasket.com/pd/126903/aashirvaad-atta-whole-wheat-5-kg-pouch/?nc=as&q=aashirwad')
f.write('\t')
f.write(str(bb_get_price('https://www.bigbasket.com/pd/126903/aashirvaad-atta-whole-wheat-5-kg-pouch/?nc=as&q=aashirwad')))
f.write('\n')
f.write('aata')
f.write('\t')
f.write("https://www.jiomart.com/p/groceries/aashirvaad-whole-wheat-atta-5-kg/490000038")
f.write('\t')
f.write(str(jio_get_price("https://www.jiomart.com/p/groceries/aashirvaad-whole-wheat-atta-5-kg/490000038")))
f.close()